apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-v2t2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-v2t2
    app.kubernetes.io/part-of: tkrw-pr712-0075-0061-app
  name: devfile-sample-v2t2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-v2t2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-v2t2
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-v2t2@sha256:ffb6a697c7b89e2500214ab7f1136f9bdb08b3aa1a41bbbada567f7cfb75bfbb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
